---
title: "Untitled"
output: html_document
date: "2026-05-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(zellkonverter)
library(SingleCellExperiment)

lung75_1 <- readH5AD("~/Desktop/adata_lung_75_rep1.h5ad")
#lung75_1
lung75_2 <- readH5AD("~/Desktop/adata_lung_75_rep2.h5ad")
#lung75_2
lung75_3 <- readH5AD("~/Desktop/adata_lung_75_rep3.h5ad")
#lung75_3
```


```{r}
meta_lung75_1 <- as.data.frame(colData(lung75_1))

raw_counts_lung75_1 <- assay(lung75_1, "counts")

lung75_1_seurat <- CreateSeuratObject(
  counts = raw_counts_lung75_1,
  meta.data = meta_lung75_1
)

lung75_1_list <- SplitObject(lung75_1_seurat, split.by = "batch")

lung75_1_list <- lapply(lung75_1_list, function(x) {
  x <- NormalizeData(x, verbose = FALSE)
  x <- FindVariableFeatures(
    x,
    selection.method = "vst",
    nfeatures = 2000,
    verbose = FALSE
  )
  x
})

features_lung75_1 <- SelectIntegrationFeatures(object.list = lung75_1_list)

lung75_1_list <- lapply(lung75_1_list, function(x) {
  x <- ScaleData(x, features = features_lung75_1, verbose = FALSE)
  x <- RunPCA(x, features = features_lung75_1, verbose = FALSE)
  x
})

lung75_1_anchors <- FindIntegrationAnchors(
  object.list = lung75_1_list,
  anchor.features = features_lung75_1,
  reduction = "rpca"
)

lung75_1_integrated <- IntegrateData(anchorset = lung75_1_anchors)

DefaultAssay(lung75_1_integrated) <- "integrated"

lung75_1_integrated <- ScaleData(lung75_1_integrated, verbose = FALSE)
lung75_1_integrated <- RunPCA(lung75_1_integrated, npcs = 30, verbose = FALSE)
lung75_1_integrated <- RunUMAP(lung75_1_integrated, reduction = "pca", dims = 1:30)
lung75_1_integrated <- FindNeighbors(lung75_1_integrated, reduction = "pca", dims = 1:30)
lung75_1_integrated <- FindClusters(lung75_1_integrated, resolution = 0.5)
```


```{r}
meta_out_lung75_1 <- lung75_1_integrated@meta.data
meta_out_lung75_1$cell_id <- rownames(meta_out_lung75_1)
meta_out_lung75_1$cluster <- meta_out_lung75_1$integrated_snn_res.0.5

pca_out_lung75_1 <- as.data.frame(Embeddings(lung75_1_integrated, "pca")[, 1:30])
colnames(pca_out_lung75_1) <- paste0("PC_", 1:30)
pca_out_lung75_1$cell_id <- rownames(pca_out_lung75_1)

export_out_lung75_1 <- merge(meta_out_lung75_1, pca_out_lung75_1, by = "cell_id")

write.csv(
  export_out_lung75_1,
  "~/Desktop/lung_seurat_75_rep1.csv",
  row.names = FALSE
)
```


```{r}

meta_lung75_2 <- as.data.frame(colData(lung75_2))

raw_counts_lung75_2 <- assay(lung75_2, "counts")

lung75_2_seurat <- CreateSeuratObject(
  counts = raw_counts_lung75_2,
  meta.data = meta_lung75_2
)

lung75_2_list <- SplitObject(lung75_2_seurat, split.by = "batch")

lung75_2_list <- lapply(lung75_2_list, function(x) {
  x <- NormalizeData(x, verbose = FALSE)
  x <- FindVariableFeatures(
    x,
    selection.method = "vst",
    nfeatures = 2000,
    verbose = FALSE
  )
  x
})

features_lung75_2 <- SelectIntegrationFeatures(object.list = lung75_2_list)

lung75_2_list <- lapply(lung75_2_list, function(x) {
  x <- ScaleData(x, features = features_lung75_2, verbose = FALSE)
  x <- RunPCA(x, features = features_lung75_2, verbose = FALSE)
  x
})

lung75_2_anchors <- FindIntegrationAnchors(
  object.list = lung75_2_list,
  anchor.features = features_lung75_2,
  reduction = "rpca"
)

lung75_2_integrated <- IntegrateData(anchorset = lung75_2_anchors)

DefaultAssay(lung75_2_integrated) <- "integrated"

lung75_2_integrated <- ScaleData(lung75_2_integrated, verbose = FALSE)
lung75_2_integrated <- RunPCA(lung75_2_integrated, npcs = 30, verbose = FALSE)
lung75_2_integrated <- RunUMAP(lung75_2_integrated, reduction = "pca", dims = 1:30)
lung75_2_integrated <- FindNeighbors(lung75_2_integrated, reduction = "pca", dims = 1:30)
lung75_2_integrated <- FindClusters(lung75_2_integrated, resolution = 0.5)
```

```{r}
meta_out_lung75_2 <- lung75_2_integrated@meta.data
meta_out_lung75_2$cell_id <- rownames(meta_out_lung75_2)
meta_out_lung75_2$cluster <- meta_out_lung75_2$integrated_snn_res.0.5

pca_out_lung75_2 <- as.data.frame(Embeddings(lung75_2_integrated, "pca")[, 1:30])
colnames(pca_out_lung75_2) <- paste0("PC_", 1:30)
pca_out_lung75_2$cell_id <- rownames(pca_out_lung75_2)

export_out_lung75_2 <- merge(meta_out_lung75_2, pca_out_lung75_2, by = "cell_id")

write.csv(
  export_out_lung75_2,
  "~/Desktop/lung_seurat_75_rep2.csv",
  row.names = FALSE
)

```




```{r}
meta_lung75_3 <- as.data.frame(colData(lung75_3))

raw_counts_lung75_3 <- assay(lung75_3, "counts")

lung75_3_seurat <- CreateSeuratObject(
  counts = raw_counts_lung75_3,
  meta.data = meta_lung75_3
)

lung75_3_list <- SplitObject(lung75_3_seurat, split.by = "batch")

lung75_3_list <- lapply(lung75_3_list, function(x) {
  x <- NormalizeData(x, verbose = FALSE)
  x <- FindVariableFeatures(
    x,
    selection.method = "vst",
    nfeatures = 2000,
    verbose = FALSE
  )
  x
})

features_lung75_3 <- SelectIntegrationFeatures(object.list = lung75_3_list)

lung75_3_list <- lapply(lung75_3_list, function(x) {
  x <- ScaleData(x, features = features_lung75_3, verbose = FALSE)
  x <- RunPCA(x, features = features_lung75_3, verbose = FALSE)
  x
})

lung75_3_anchors <- FindIntegrationAnchors(
  object.list = lung75_3_list,
  anchor.features = features_lung75_3,
  reduction = "rpca"
)

lung75_3_integrated <- IntegrateData(anchorset = lung75_3_anchors)

DefaultAssay(lung75_3_integrated) <- "integrated"

lung75_3_integrated <- ScaleData(lung75_3_integrated, verbose = FALSE)
lung75_3_integrated <- RunPCA(lung75_3_integrated, npcs = 30, verbose = FALSE)
lung75_3_integrated <- RunUMAP(lung75_3_integrated, reduction = "pca", dims = 1:30)
lung75_3_integrated <- FindNeighbors(lung75_3_integrated, reduction = "pca", dims = 1:30)
lung75_3_integrated <- FindClusters(lung75_3_integrated, resolution = 0.5)
```

```{r}
meta_out_lung75_3 <- lung75_3_integrated@meta.data
meta_out_lung75_3$cell_id <- rownames(meta_out_lung75_3)
meta_out_lung75_3$cluster <- meta_out_lung75_3$integrated_snn_res.0.5

pca_out_lung75_3 <- as.data.frame(Embeddings(lung75_3_integrated, "pca")[, 1:30])
colnames(pca_out_lung75_3) <- paste0("PC_", 1:30)
pca_out_lung75_3$cell_id <- rownames(pca_out_lung75_3)

export_out_lung75_3 <- merge(meta_out_lung75_3, pca_out_lung75_3, by = "cell_id")

write.csv(
  export_out_lung75_3,
  "~/Desktop/lung_seurat_75_rep3.csv",
  row.names = FALSE
)

```



# fastMNN

```{r}
set.seed(123)

lung75_1 <- logNormCounts(lung75_1)

dec_lung75_1 <- modelGeneVar(lung75_1)
chosen_hvgs_lung75_1 <- getTopHVGs(dec_lung75_1, n = 2000)

lung75_1_mnn <- fastMNN(
  lung75_1,
  batch = lung75_1$batch,
  subset.row = chosen_hvgs_lung75_1
)

colData(lung75_1_mnn)$cell_type <- colData(lung75_1)$cell_type

metadata(lung75_1_mnn)$merge.info <- NULL
writeH5AD(lung75_1_mnn, "~/Desktop/lung75_1_fastmnn.h5ad")
```



```{r}
set.seed(123)

lung_list <- list(
  lung75_1 = lung75_1,
  lung75_2 = lung75_2,
  lung75_3 = lung75_3
)

lung_mnn_list <- list()

for (nm in names(lung_list)) {
  
  sce_obj <- lung_list[[nm]]
  
  sce_obj <- logNormCounts(sce_obj)
  dec_obj <- modelGeneVar(sce_obj)
  chosen_hvgs_obj <- getTopHVGs(dec_obj, n = 2000)
  
  mnn_obj <- fastMNN(
    sce_obj,
    batch = sce_obj$batch,
    subset.row = chosen_hvgs_obj
  )
  
  colData(mnn_obj)$cell_type <- colData(sce_obj)$cell_type
  
  lung_mnn_list[[nm]] <- mnn_obj
  
  metadata(mnn_obj)$merge.info <- NULL
  out_path <- paste0("~/Desktop/", nm, "_fastmnn.h5ad")
  writeH5AD(mnn_obj, out_path)
  
}
```





