---
title: "Untitled"
output: html_document
date: "2026-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(zellkonverter)
library(SingleCellExperiment)

lung_sce <- readH5AD("~/Desktop/adata_lung_qc.h5ad")
lung_sce
```


```{r}
raw_counts <- assay(lung_sce, "counts")

dim(raw_counts)
raw_counts[1:5, 1:5]
```


```{r}
library(Seurat)

meta <- as.data.frame(colData(lung_sce))

lung_seurat <- CreateSeuratObject(
  counts = raw_counts,
  meta.data = meta
)

lung.list <- SplitObject(lung_seurat, split.by = "batch")

lung.list <- lapply(lung.list, function(x) {
  x <- NormalizeData(x, verbose = FALSE)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
  x
})

features <- SelectIntegrationFeatures(object.list = lung.list)

lung.list <- lapply(lung.list, function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
  x
})

lung.anchors <- FindIntegrationAnchors(
  object.list = lung.list,
  anchor.features = features,
  reduction = "rpca"
)

lung.integrated <- IntegrateData(anchorset = lung.anchors)

DefaultAssay(lung.integrated) <- "integrated"

lung.integrated <- ScaleData(lung.integrated, verbose = FALSE)
lung.integrated <- RunPCA(lung.integrated, npcs = 30, verbose = FALSE)
lung.integrated <- RunUMAP(lung.integrated, reduction = "pca", dims = 1:30)
lung.integrated <- FindNeighbors(lung.integrated, reduction = "pca", dims = 1:30)
lung.integrated <- FindClusters(lung.integrated, resolution = 0.5)
```



```{r}
library(SeuratDisk)
SaveH5Seurat(
  lung.integrated,
  filename = "~/Desktop/lung_integrated.h5Seurat",
  overwrite = TRUE
)
Convert(
  "~/Desktop/lung_integrated.h5Seurat",
  dest = "h5ad",
  overwrite = TRUE
)
```


#fastMNN

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("batchelor")
```

```{r}
library(batchelor)
library(scran)
library(scater)
```

```{r}
set.seed(123)

lung_sce <- logNormCounts(lung_sce)

dec <- modelGeneVar(lung_sce)
chosen_hvgs <- getTopHVGs(dec, n = 2000)

lung_mnn <- fastMNN(
  lung_sce,
  batch = lung_sce$batch,
  subset.row = chosen_hvgs
)
```

```{r}
colData(lung_mnn)$cell_type <- colData(lung_sce)$cell_type
```


```{r}
library(zellkonverter)
metadata(lung_mnn)$merge.info <- NULL
writeH5AD(lung_mnn, "~/Desktop/lung_fastmnn.h5ad")
```










